### ISSUE TITLE
LSP crahes when running on `asm_return_tuple_pointer` example

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1385]
Trying to save in vscode with https://github.com/FuelLabs/sway/tree/87b734cb9f63dc15b0dce376f63ad1c59de09894/examples/asm_return_tuple_pointer open crashes the LSP server. Likely due to the asm.

**Comment by JoshuaBatty** [comment]
Hi @adlerjohn i'm not able to reproduce this using that example. What indication were you seeing that showed the server as having crashed? Are there any errors reported in the output window for the client or server?

**Comment by adlerjohn** [comment]
I can reproduce it using the latest `master` of this repo. I specifically tried cdd35dcd2f44660eeb7e2c940471c8ef4b33cffd just now. Make sure you're compiling everything with `cargo b --workspace --all-features` just in case.

```text
thread 'main' panicked at 'attempt to subtract with overflow', sway-lsp/src/capabilities/semantic_tokens.rs:56:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:54:48 AM] Connection to server got closed. Server will restart.
[Error - 1:54:48 AM] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
	at Object.dispose (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireClose (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at Socket.<anonymous> (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 1:54:48 AM] Request textDocument/formatting failed.
Error: Connection got disposed.
	at Object.dispose (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireClose (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at Socket.<anonymous> (/home/john/.vscode/extensions/fuellabs.sway-vscode-plugin-0.2.2/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
[Info  - 1:54:48 AM] Initializing the Sway Language Server
[Info  - 1:54:48 AM] Sway Language Server Initialized
thread 'main' panicked at 'attempt to subtract with overflow', sway-lsp/src/capabilities/semantic_tokens.rs:56:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by JoshuaBatty** [comment]
So it looks like there is a bug with the parser. I've outlined my findings in #1395. Essentially the parser is reporting a garbage name so when we traverse the tree to collect tokens, the token name is an incorrect large string. This is leading to the `attempt to subtract with overflow` error in the semantic_tokens code as the token name is incorrect.

**Comment by canndrew** [comment]
Has this been fixed by https://github.com/FuelLabs/sway/pull/1542?

**Comment by adlerjohn** [comment]
@canndrew No, looks like it's still happening with current `master` (bc724b489805f9289fcf1a4a443e635c4f67cd92).
